/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		AGENT_ACCESS_PASSWORD?: string;
		AGENT_AUTH_TOKEN?: string;
		AGENT_SESSION_SECRET?: string;
		SUPABASE_URL?: string;
		SUPABASE_SERVICE_ROLE_KEY?: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
